#!/bin/bash

echo "Bitcoin Node Monitor - Help Guide"
echo "================================="
echo ""
echo "Available Commands:"
echo ""
echo "1. Monitoring Commands:"
echo "   ./monitor.sh              - Start real-time monitoring dashboard (10s intervals)"
echo "   ./btc-monitor             - Continuous monitoring dashboard (30s intervals)"
echo "   ./btc-tools all           - Show one-time complete status"
echo "   ./btc-tools node          - Show node status only"
echo "   ./btc-tools price         - Show current price information"
echo "   ./btc-tools supply        - Show supply statistics"
echo "   ./btc-tools health        - Check node health"
echo ""
echo "2. Quick Information:"
echo "   ./btcprice                - Quick Bitcoin price check"
echo "   ./btc-fees                - Current network fees"
echo "   ./supply_calc.sh          - Detailed supply analysis"
echo ""
echo "3. Configuration:"
echo "   ./btc-monitor-alerts      - Monitoring with alerts"
echo "   ./btccli                  - Direct Bitcoin Core CLI access"
echo ""
echo "4. Shortcuts (if configured):"
echo "   btcm                      - Start monitoring dashboard"
echo "   btcp                      - Quick price check"
echo "   btcf                      - Network fees"
echo "   btct [command]            - Run btc-tools commands"
echo ""
echo "For more information, visit:"
echo "https://github.com/MatchaBear/bitcoin-node-monitor"
echo ""

